### PR TITLE
Add an example systemd.service

### PR DESCRIPTION
**Pull request by felagund**
It took me a while to figure it out what exactly to put into the service file, I guess it will be helpful for others too.

### CODE REVIEW

**Comment by yunmikun2** [comment]
After [the PR about `uinput` necessity](https://github.com/samvel1024/kbct/pull/26) I wonder if it would be better to include loading `uinput` module in `PreExec` step, so users won't need to think about it?

**Comment by felagund** [comment]
Ok, I then also moved the remark about loading the module to troubleshooting.

**Comment by NoahTheDuke** [comment]
This helped me a lot, thanks for the PR. Hope it can get merged so others benefit too.

**Comment by RichardFevrier** [comment]
Here is my config since yours wasn't working on my **Fedora Silverblue** if ever someone need it:

```
[Unit]
Description=Keyboard keycode mapping daemon supporting layered configuration
[Service]
Type=simple
ExecStartPre=modprobe uinput
ExecStart=/bin/bash -c "/usr/local/bin/kbct remap --config /etc/kbct/config.yml"
Restart=always
[Install]
WantedBy=default.target
```

**Comment by felagund** [comment]
Yeah, you are right, I had typoes there it seems, added to the commit.

**Comment by RichardFevrier** [comment]
Also I needed `/bin/bash -c ...`

**Comment by felagund** [comment]
I see. Added link to   `/bin/sh`

**Pull request merged**
